load("@pip//:requirements.bzl", "requirement")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "topic",
    srcs = ["topic.py"],
    deps = [
        requirement("redis"),
    ],
)
